import Head from "next/head";
import { Analytics } from "@vercel/analytics/react"
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import Image from "next/image";
import peeps from "../public/peeps-avatar-alpha.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import Calendar from "../public/CalendarDesign.png";
import SignUp from "../public/SignUp.png";
import LandingPage from "../public/LandingPage.png";
import BlogNode from "../public/astro-blog-node.png";
import { useState } from "react";
// import NextLink from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Rajeev Krishna Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-5 md:px-20 lg:px-40 dark:bg-black">
        <section id="footer" className="min-h-screen">
          <nav className="p-10 flex justify-between rounded-md">
            <h1 className="text-2xl font-semibold dark:text-white">rajeev krishna</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl dark:text-white"
               />
              </li>
              <li>
                <a
                  className="font-bolder bg-gradient-to-r from-teal-200 to-fuchsia-200 px-4 py-2 rounded-md ml-8 font-semibold dark:shadow-slate-400 hover:shadow-lg"
                  href="https://drive.google.com/file/d/1Zxz5-aqpnUENfsCXMndn_ZJlimpeAev3/view?usp=drive_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center mt-10 p-10">
            <h2 className="text-6xl py-2 font-semibold text-teal-600 font-medium md:text-6xl">
              rajeev krishna
            </h2>
            <h3 className="text-3xl py-2 md:text-4xl dark:text-white">
            frontend engineer
            </h3>
            <p className="my-10 text-md py-2 leading-7 text-gray-500 md:text-xl max-w-lg mx-auto">
              an aspiring frontend engineer with a passion for css and zest for TailwindCSS. with a keen interest in design and development and hands-on experience using Figma and Webflow for UI/UX and no-code tools.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-10 text-gray-500">
            <a href="https://twitter.com/RadzhivDev">
              <AiFillTwitterCircle className="hover:text-blue-700 cursor-pointer" />
            </a>
            <a href="https://www.linkedin.com/in/rajeevkrishna25/">
              <AiFillLinkedin className="hover:text-blue-700" />
            </a>
            <a href="https://github.com/radzhiv25">
              <AiFillGithub className="hover:text-black dark:hover:text-green-600" />
            </a>
            {/* <AiFillInstagram className= 'hover:text-pink-600'/> */}
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={peeps} layout="fill" alt=""/>
          </div>
        </section>
        <section className="mt-10">
          <div>
            <h3 className="text-3xl font-semibold py-1 dark:text-white text-center">Skills I offer </h3>
            <p className="text-md py-2 leading-7 text-gray-400 text-center ">
              Since the beginning of my college studies I had started as a
              Frontend Developer and I have been making clone of{" "}
              <span className="text-teal-400">certain websites.</span>
              <br />I offer a wide range of services, including design and
              programming.
            </p>
          </div>
          <div className="lg:grid grid-cols-3 gap-10 text-center">
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              <Image src={design} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-xl font-medium pt-5 pb-2 dark:text-teal-200">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-teal-50">
                Elegant designs suited for your needs and design theory.
              </p>
              <h4 className="py-4 text-teal-400">Tools I use daily</h4>
              <ul className="tools space-y-1 dark:text-white" >
              <li>VS Code</li>
              <li>GitHub</li>
              <li>Figma</li>
              <li>Adobe XD</li>
              </ul>
            </div>
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              <Image src={code} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-lg font-medium pt-5 pb-2 dark:text-teal-200">
                Programming
              </h3>
              <p className="py-2 dark:text-teal-50">
                Programming basics as an undergrad.
              </p>
              <h4 className="py-4 text-teal-400">Languages I use for programming</h4>
              <ul className="space-y-1 dark:text-white">
                <li>HTML</li>
                <li>CSS</li>
                <li>Javascript</li>
                <li>C++</li>
              </ul>
            </div>
            <div className="shadow-lg p-5 rounded-xl my-10 dark:bg-slate-900 hover:scale-105">
              <Image src={consulting} width={100} height={100} alt="" className="relative left-1/3"/>
              <h3 className="text-lg font-medium pt-5 pb-2 dark:text-teal-200">
                Coding of Design
              </h3>
              <p className="py-2 dark:text-teal-50">
                The Design being implemented as proper website.
              </p>
              <h4 className="py-4 text-teal-400">Lirbraries and Frameworks I use</h4>
              <ul className="space-y-1 dark:text-white">
                <li>TailwindCSS</li>
                <li>React</li>
                <li>Next</li>
                <li>Astro</li>
              </ul>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-center text-3xl py-1 font-semibold dark:text-white">Projects</h3>
            <div>
              <p className="text-center text-md py-2 leading-7 text-gray-400">
                Since the beginning of my college studies I had started as a
                Frontend Developer and i have been making clone of{" "}
                <span className="text-teal-400">certain websites.</span>
                <br />I offer a wide range of services, including design and
                programming.
              </p>
            </div>
          </div>
          <div className="grid lg:grid-cols-2 grid-cols-1 gap-10 py-10">
            <div className="">
              <a href="https://radzhiv25.github.io/Projects/Calendar/index.html">
              <Image
                src={Calendar}
                className="rounded-lg object-cover border shadow-md hover:scale-105"
                width={"100%"}
                height={"100%"}
                layout="responsive" alt="" />
              </a>
            </div>
            <div className="">
              <Image
                src={SignUp}
                className="rounded-lg object-cover border shadow-md hover:scale-105"
                width={"100%"}
                height={"100%"}
                layout="responsive" alt=""/>
            </div>
            <div className="">
              <Image
                src={LandingPage}
                className="rounded-lg object-cover border shadow-md hover:scale-105"
                width={"100%"}
                height={"100%"}
                layout="responsive" alt="" />
            </div>
            <div className="">
              <a href="https://astro-blog-node.vercel.app/">
              <Image
                src={BlogNode}
                className="rounded-lg object-cover shadow-md hover:scale-105"
                width={"100%"}
                height={"100%"}
                layout="responsive" alt="" />
              </a>
            </div>
          </div>
        </section>
        <section>
          <div className="p-5 rounded-md text-center dark:text-white">
            <p className="font-bold">
              <span>
                <a href="#footer">Rajeev Krishna </a>
              </span>
              © 2023
            </p>
            <p className="mt-2">Created with NextJS and Tailwind 🚀</p>
          </div>
        </section>
      </main>
      <Analytics />
    </div>
  );
}
